Validation+tests
sehersarin/MSCI342-Term-Project pull request #16
Opened 2020-10-20 18:18 UTC by mtatran

Ticket: S3T2

Description: authentication at log-in. I passed in name and type to dashboard, and I did an example of conditional rendering to differentiate user dashboard and worker dashboard.

Note: testing will be done in another PR along with General T3

How to test: 

checkout this branch, then test the credentials of a student : johndoe@gmail.com, a1234. Check if the Header is red.
Then check the credentials of a worker : 
joshuabrooks@gmail.com, j1234. Check if the Header is blue.
Then check a faulty credential. Check if the dashboard does not appear.

2020-10-20 18:23 UTC, catai9 commented on server/package.json
> +    "query-string": "^6.13.6"
query-string should probably be installed in the package.json for the react-ui to prevent confusion as it is used for the front end.

2020-10-20 18:24 UTC, catai9 commented on react-ui/src/components/LogInForm.js
> +          firstName : res.data.firstName,
I would recommend using the studentId or workerId instead of first name since it's possible for multiple users to have the same first name

2020-10-20 18:27 UTC, catai9 requested changes
I like the flow and reuse of the same method for different user types (student and worker). Currently, the unique identifier appears to be first name. However, I would recommend using the studentId or workerId (maybe utilize a condition statement such as `userId = res.data.type ==="worker" ? workerId : studentId` to store the personId or userId. The reasoning is that multiple users may have the same first name and be of the same user type.

2020-10-20 20:25 UTC, nancyprabhakar submitted a review, later dismissed
Hi Melissa,

I've commented on the areas where I feel the terminology is inconsistent with the backend for user login/account creation.  I would recommend keeping the identifiers consistent with the backend user login/account creation terminology. Check out the way students and service staff are stored in > MSCI342-Term-Project/server/models/data/Student.js / and MSCI342-Term-Project/server/models/data/Worker.js /

2020-10-20 20:25 UTC, nancyprabhakar commented on react-ui/src/components/Layouts/Dashboard.js
> -                <Page2 name={this.state.personId}/>
Hi Melissa, 
Is personId a unique identified for both students and service staff? I would recommend keeping the identifiers consistent with the backend user login/account creation terminology. Check out the way students and service staff are stored in > MSCI342-Term-Project/server/models/data/Student.js / and MSCI342-Term-Project/server/models/data/Worker.js /

2020-10-20 20:25 UTC, nancyprabhakar commented on react-ui/src/components/LogInForm.js
> -        user_password: "",
I would suggest to use email instead of user_id.
For a student, the credentials we use are: 
firstName
lastName
email
accessToken
phone
schoolID

For a Service Staff, the credentials are:
workerID
firstName
lastName
email
accessToken
phone
specialization

User_ID is not one of the credentials in either scenario.

2020-10-20 20:25 UTC, nancyprabhakar commented on react-ui/src/components/LogInForm.js
> -                  name="user_id"
I'd recommend keeping the terminology consistent with the Student and Worker objects. For user_ID and user_password: Check out the way students and service staff are stored in > MSCI342-Term-Project/server/models/data/Student.js / and MSCI342-Term-Project/server/models/data/Worker.js /

2020-10-21 16:38 UTC, catai9 commented on react-ui/src/components/LogInForm.js
> +      name: "",
Minor change, but I would recommend renaming it to firstName to increase code readability in the future.

2020-10-21 17:08 UTC, catai9 commented
When I test faulty credentials, the webpage shows without any error states. Is this intended?
![image](https://user-images.githubusercontent.com/32720322/96753917-8f9b1d00-139e-11eb-829d-f3ea63bf5bec.png)

2020-10-22 00:39 UTC, catai9 approved these changes
Great work Melissa! Thank you for addressing the raised concerns.

As per the description for this pull request, I understand that the unit testing for this feature will be included for the scope of a future task under this story and that this story is not yet complete. In addition, after our conversation with the team and between ourselves, we have decided that error handling for invalid user credentials is outside the scope of this task. Thus, this scope of this pull request only involves rendering different header colours given the user type (with the worker header colour shown as default) and integrating the form with the back end endpoint `api/login`.

I have also ran the code locally by running `npm run-script start:dev` in the root folder and tested both valid student and worker credentials (listed in the pull request description) to ensure that the appropriate header colour was displayed, along with the proper user first name in the url (shown below). I also tested invalid credentials to check that the default header colour (corresponding to the worker user type) was shown. Although it did not appear that there was any server code changed, I also ran the automated tests in the server folder (no tests currently set up for the react-ui folder) with the command `npm test` to ensure all tests still passed and had 100% code coverage for all files.

As such, I am approving this PR and I will be merging it into master!

**Worker Credentials (Joshua):**
![image](https://user-images.githubusercontent.com/32720322/96804391-de67a780-13dc-11eb-943b-b8b4d2908200.png)

**Student Credentials (John):**
![image](https://user-images.githubusercontent.com/32720322/96804446-05be7480-13dd-11eb-8521-d95e7ed4a96b.png)

**Invalid Credentials (No Name):**
![image](https://user-images.githubusercontent.com/32720322/96753917-8f9b1d00-139e-11eb-829d-f3ea63bf5bec.png)

2020-10-22 00:42 UTC, merged